version: "3"
services:
  all:
    image: juunary/webpage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      NODE_ENV: production
