# Dockerfile.dev (개발 환경)

# 최신 버전의 Node.js를 사용하는 도커 이미지를 지정합니다.
FROM node:latest

# 앱 소스코드를 복사할 디렉토리를 지정합니다.
WORKDIR '/app'

# package.json 및 package-lock.json을 복사하여 종속성을 먼저 설치합니다.
COPY package.json .
COPY package-lock.json .
RUN npm install

# 소스 코드를 현재 디렉토리로 복사합니다.
COPY . .

# Python을 설치합니다.
RUN apt-get update || : && apt-get install python3 -y python3-pip python3-venv

# 가상 환경을 생성하고 활성화합니다.
RUN python3 -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

# 가상 환경 내에서 Python 패키지를 설치합니다.
RUN pip3 install numpy
RUN pip3 install xgboost 
RUN pip3 install pandas 
RUN pip3 install scikit-learn

# 개발 서버를 시작합니다.
CMD ["npm", "run", "start"]
