name: Deploy bicycle-website
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # frontend 이미지 빌드 및 푸시
      - run: docker build -t juunary/webpage .
      - run: docker push juunary/webpage


      # 배포용 압축 파일 생성
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # Elastic Beanstalk로 배포
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: plz-git-action
          environment_name: Plz-git-action-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-645379147304
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
